Add project logic and check mark images
jamie-jungah/react-next-recoil-tailwind-practice pull request #8
Opened 2022-11-21 10:43 UTC by jamie-jungah

1. Todo 앱 구현에 필요한 기본적인 로직들을 다 짰습니다.
2. figma에서 가져온 check mark 이미지를 추가했습니다.

2022-11-21 10:47 UTC, jamie-jungah commented
충돌난 부분은 다 해결해서 업데이트 했습니다!

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/pages/Todo.tsx
>  const Todo: React.FC = () => {
해당 부분의 컴포넌트명과 파일명을 `TodoPage.tsx` 으로 지정하는 것이 좋을 것 같습니당.
Page는 라우팅으로만 사용하기 때문입니다.

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/pages/Todo.tsx
>              </header>
해당 부분은 `features/Todo/components` 내부 디렉토리의 `<TodoHeader />` 로 분리할 수 있겠습니다.

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/pages/Todo.tsx
>              </header>
TodoHeader 내부에서 아래와 같이 `React.memo()` 를 통해 리렌더링이 일어나지 않도록 최적화가 가능합니다.

```ts
const TodoHeader: React.FC = () => { // .... }
export default React.memo(TodoHeader); 
```

꼭 필수적인 부분은 아니지만, 유용한 최적화 테크닉이니 이해하시는 것이 좋습니당

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/pages/Todo.tsx
> +            <TodoForm/>
아주 잘 묶으셨네요! 👍

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/components/TodoForm.tsx
> +export type Todo = {
해당 부분은 type으로 작성할 수 있겠지만, interface를 이용하는 것을 추천드립니다!
type을 사용하는 경우는 여러 타입들을 아래와 같이 합성하는 경우에 유용하오니, 단위 타입에 대해서는 왠만하면 interface를 이용하는 것을 추천드립니다.

```ts
type Cat = Animal & Mammal && Meow;
```

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/components/TodoForm.tsx
> +    const timestamp = () => {
해당 함수는 `features/Todo/utils` 의 `getCurrentTimestamp()` 로 분리할 수 있겠습니다!

더불어서 해당 함수는 컴포넌트 내부에서 선언될 필요가 없습니당.(상태값을 이용해서 가공하는 함수가 아니기 때문이며 순수함수이기 때문!)

함수를 컴포넌트 내부에서 생성하게 되면 컴포넌트가 렌더링 될 때 마다 해당 함수를 또 만들어야 하기 때문입니다.

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/components/TodoForm.tsx
> +        return today.toISOString().replace('T', ' ').substring(0, 19);
음... 일단 이런식으로 시간값을 분리하는 것도 좋은 방법이지만 날짜, 시간 데이터를 다루기 위한 라이브러리인 https://date-fns.org/ 도 유용합니당

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/components/TodoForm.tsx
> +    const handleInput = (event: React.ChangeEvent<HTMLInputElement>) => {
해당 이벤트 함수는 아래와 같이 최적화 할 수 있겠습니다.
```ts
const handleInput = useCallback((e) => { 
//.. 
}, []);
```

https://react.vlpt.us/basic/18-useCallback.html 요기 아티클을 참고해보세용!

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/components/TodoForm.tsx
> +    const handleFormSubmit = (event: React.FormEvent) => {
https://react.vlpt.us/basic/18-useCallback.html 요기 아티클을 참고해보세용!

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/components/TodoForm.tsx
> +    const handleChange = (todo: Todo) => {
https://react.vlpt.us/basic/18-useCallback.html 요기 아티클을 참고해보세용!

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/components/TodoForm.tsx
> +        todos.splice(index, 1, todo);
참고로 함수 파라미터의 todos를 이와 같이 조작하려고 하는 것은 어쩌면 위험한 테크닉입니다. 물론 잘 동작하는 경우도 있지만 왠만하면 내부에서 변수에 복사하거나, 분리하여 사용하는 것을 추천드립니다!

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/components/TodoForm.tsx
> +    const handleDelete = (id: number) => {
https://react.vlpt.us/basic/18-useCallback.html 요기 아티클을 참고해보세용!

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/components/TodoForm.tsx
> +        <div className="todo-contents-wrapper">
ㅎㅎ class를 일일히 지정하지 않아도 됩니당.

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/components/TodoItem.tsx
> +                <h5>{datetime}</h5>
마크업을 하실 때 조금 더 의미있게 작성하는 것이 중요합니다!
물론 미미한 차이지만 디테일이 가미된 마크업은 SEO에서 중요한 역할을 해요!

- 해당 TodoItem은 사실 "목록의 한 아이템" 에 해당 됩니다. 따라서, `<li></li>` 태그로 감싸주는 것이 좋습니다.
- TodoItem의 상위는 `<ul></ul>` 로 감싸진 부모 컴포넌트가 있어야 합니다! 
- 카드 내부에서 제목태그인 `<h3>` 와 `<h4>` 태그를 사용하셨는데, `<h3>` 대신에 `<span>` 태그가 적절하고, `<h5>` 역시 `<span>` 또는 `<time>`이 적절할 듯 싶습니다!

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/components/TodoItem.tsx
> +                checkmark
여기에 이미지를 넣으실 때에는 
`<img src=[ public 내부의 상태 경로 ] width={} height={} alt="" />`
이런식으로 작성하시면 됩니다!

경로는 그러면 `/assets/check-circle.png` 가 되겠네용

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/components/TodoItem.tsx
> +                checkmark
더불어서 해당 부분의 마크업은 `<button />` 이 적절합니다.

2022-11-21 11:16 UTC, aiiiden commented on features/Todo/components/TodoForm.tsx
> +            ))}
해당 부분은 `<ul />`을 사용하여 `<TodoList />` 로 한번 더 묶으면 좋을 것 같습니다!

2022-11-21 11:22 UTC, Phantola commented on features/Todo/components/TodoForm.tsx
> +        return today.toISOString().replace('T', ' ').substring(0, 19);
유저에이전트( 브라우저 ) 가 자동으로 타임존에 맞게 해석해서 강제로 9시간을 더하면 실제로는 UTC + 18 이되버립니다.
+9 는 빼주셔도 좋을 것 같아요

2022-11-21 11:26 UTC, aiiiden requested changes
실행후 테스트까지 잘 동작하는 것을 확인했습니다! 입력값에 따른 validation과 trim 처리를 해주신것에서 @jamie-jungah 님의 꼼꼼함이 돋보였습니다! 제가 작성한 리뷰는 프로젝트에 사용되는 일종의 컨벤션과 같은 것이니 확인후 수정해주시면 감사하겠습니다!

2022-11-21 11:36 UTC, aiiiden commented on features/Todo/components/TodoForm.tsx
> +        setTodos([...todos]);
여기서 todo는 함수의 인자값입니다. 인자값을 직접 수정하게 되면 call by reference로 접근하게 되는 것이라서 원본 객체가 수정될 위험이 있습니다!

명시적으로 아래와 같이 작성하시는 것이 좋습니다!
```ts
const handleChange = (todo: Todo) => {
        const index = todos.indexOf(todo);
        const newTodo = { ...todo, isCompleted: !todo.isCompleted };
        
        setTodos([
            ...todos.slice(0, index),
            newTodo,
            ...todos.slice(index + 1, todos.length),
        ]);
    }
```

2022-11-22 09:09 UTC, jamie-jungah commented on features/Todo/components/TodoForm.tsx
> +        return today.toISOString().replace('T', ' ').substring(0, 19);
> 유저에이전트( 브라우저 ) 가 자동으로 타임존에 맞게 해석해서 강제로 9시간을 더하면 실제로는 UTC + 18 이되버립니다. +9 는 빼주셔도 좋을 것 같아요

흠.. 그런데 왜 제 노트북에서는 UTC 시간으로 나타날까용..?

2022-11-22 09:16 UTC, aiiiden commented on features/Todo/components/TodoForm.tsx
> +        return today.toISOString().replace('T', ' ').substring(0, 19);
@jamie-jungah OS 설정에 따라 다르게 나타납니다.

2022-11-22 09:18 UTC, aiiiden commented on features/Todo/components/TodoForm.tsx
> +        return today.toISOString().replace('T', ' ').substring(0, 19);
```
// 1. 현재 시간(Locale)
const curr = new Date();

// 2. UTC 시간 계산
const utc = 
      curr.getTime() + 
      (curr.getTimezoneOffset() * 60 * 1000);

// 3. UTC to KST (UTC + 9시간)
const KR_TIME_DIFF = 9 * 60 * 60 * 1000;
const kr_curr = 
      new Date(utc + (KR_TIME_DIFF));
```

만약 순수자바스크립트로 구현한다면 사실은 이렇게 되어야 합니당

2022-11-22 09:19 UTC, aiiiden commented on features/Todo/components/TodoForm.tsx
> +        return today.toISOString().replace('T', ' ').substring(0, 19);
근데 저희같은 해외서비스의 경우에는 UTC 기준으로 보여주는 것이 좋습니당 대신에 시간 뒤에 UTC라고 정확히 표현만 하면 됩니다.

2022-11-23 06:19 UTC, aiiiden approved these changes
수고많으셨습니다 ㅠㅠ

2022-11-23 06:22 UTC, merged